### PR TITLE
Add chacha20-ietf cipher - Fixes #131

### LINKED ISSUE #131: Unsupported encryption method: chacha20-ietf
Unsupported encryption method: chacha20-ietf
Unsupported encryption method: chacha20-ietf
Unsupported encryption method: chacha20-ietf
Unsupported encryption method: chacha20-ietf
Unsupported encryption method: chacha20-ietf
Unsupported encryption method: chacha20-ietf
Unsupported encryption method: chacha20-ietf

https://shadowsocks.org/en/spec/cipher.html

### PR DESCRIPTION
**Pull request by aead**
Adding the ChaCha20 cipher specified [RFC 7539](https://tools.ietf.org/html/rfc7539)
https://shadowsocks.org/en/spec/cipher.html

### CODE REVIEW

**Comment by lixin9311** [comment]
Sorry for not reading carefully.
Seems like the package from golang sub-repo is not optimized using asm.
I'll run some tests and merge it.

**Comment by lixin9311** [comment]
It seems [github.com/Yawning/chacha20](https://github.com/Yawning/chacha20) has provided standard chacha20 block function with a branch of other variants with a fair performance (comparison here #187).

If you could implement more chacha20 variants, it will be great to merge your code.
But, for now, I prefer #187.

I will keep this open.

**Comment by aead** [comment]
The [chacha20](https://github.com/aead/chacha20) repo was developed with the ChaCha20Poly1305 AEAD in mind. Go added an implementation for ChaCha20Poly1305 (but probably won't add a ChaCha20 / XChaCha20/12/8 package) - so I think it's the right time to restart and focus just on ChaCha20 (and its variants). 
But currently some other repos rely on the code and I don't want to break their builds - so this can take some time...

**Comment by lixin9311** [comment]
Fix in #205

**Pull request closed without merging**
