### PR TITLE
add mirror server

### PR DESCRIPTION
**Pull request by houstar**
This patch added command shadowsocks-mirror-server which mirror the remote 
shadowsocks-server to local and use the shadowsocks-server as gateway in fact.

### CODE REVIEW

**Comment by arthurkiller** [comment]
thx for your contribute.

But, what is mirror server?

**Comment by arthurkiller** [comment]
shadowsocks remote server should only communicate with local via shadowsocks protocol.

I did not understand what kind of problem you are facing while use shadowsocks-go

**Comment by houstar** [comment]
@arthurkiller thanks for you quick reply.

Let's me show the diff between original shadowsocks-server and shadowsocks-mirror-server.
The original shadowsocks-server will not use the json configuration's server field.
The shadowsocks-mirror-server will use the json configuration's server field to dial shadowsocks-server.

Conclusion: shadowsocks-mirror-server have the same configuration as shadowsocks-server did,
but all the network stream will be sent to shadowsocks-server. 

The User Case is that:

1. multiple shadowsocks client to connect shadow-server will be detect by GFW.
2. so this solution :
    the stream is: multiple shadowsocks client -> shadowsocks-mirror-server -> shadowsocks-server 
    the shadowsocks-mirror-server is inside the firewall and GFW will only see one connection to 
    shadowsocks-server

``` 
diff -Naru cmd/shadowsocks-server/server.go cmd/shadowsocks-mirror-server/server.go
--- cmd/shadowsocks-server/server.go	2018-07-18 00:16:45.000000000 +0800
+++ cmd/shadowsocks-mirror-server/server.go	2018-07-18 03:23:11.000000000 +0800
@@ -106,7 +106,7 @@
   }
 }

-func handleConnection(conn *ss.Conn, port string) {
+func handleConnection(conn *ss.Conn, config *ss.Config, port string) {
 	var host string

 	connCnt++ // this maybe not accurate, but should be enough
@@ -147,7 +147,14 @@
 		return
 	}
 	debug.Println("connecting", host)
-	remote, err := net.Dial("tcp", host)
+	rawAddr, err := ss.RawAddr(host)
+	if err != nil {
+		panic("Error getting raw address.")
+	}
+    remote, err := ss.DialWithRawAddr(
+        rawAddr,
+        net.JoinHostPort(config.Server.(string), strconv.Itoa(config.ServerPort)),
+        conn.Cipher.Copy())
 	if err != nil {
 		if ne, ok := err.(*net.OpError); ok && (ne.Err == syscall.EMFILE || ne.Err == syscall.ENFILE) {
 			// log too many open file error
@@ -157,7 +164,7 @@
 			log.Println("error connecting to:", host, err)
 		}
 		return
-	}
+    }
 	defer func() {
 		if !closed {
 			remote.Close()
@@ -369,7 +376,7 @@
 				continue
 			}
 		}
-		go handleConnection(ss.NewConn(conn, cipher.Copy()), port)
+		go handleConnection(ss.NewConn(conn, cipher.Copy()), config, port)
 	}
 }

@@ -404,7 +411,7 @@
 }

 func enoughOptions(config *ss.Config) bool {
-	return config.ServerPort != 0 && config.Password != ""
+	return config.Server != nil && config.ServerPort != 0 && config.Password != ""
 }

 func unifyPortPassword(config *ss.Config) (err error) {
@@ -430,11 +437,13 @@
 	log.SetOutput(os.Stdout)

 	var cmdConfig ss.Config
+    var cmdServer string
 	var printVer bool
 	var core int

 	flag.BoolVar(&printVer, "version", false, "print version")
 	flag.StringVar(&configFile, "c", "config.json", "specify config file")
+	flag.StringVar(&cmdServer, "s", "", "server address")
 	flag.StringVar(&cmdConfig.Password, "k", "", "password")
 	flag.IntVar(&cmdConfig.ServerPort, "p", 0, "server port")
 	flag.IntVar(&cmdConfig.Timeout, "t", 300, "timeout in seconds")
@@ -451,6 +460,7 @@
 		os.Exit(0)
 	}

+    cmdConfig.Server = cmdServer
 	ss.SetDebug(debug)

 	var err error

```

**Comment by arthurkiller** [comment]
I did not understand why 
> multiple shadowsocks client to connect shadow-server will be detect by GFW.

and why 
> the stream is: multiple shadowsocks client -> shadowsocks-mirror-server -> shadowsocks-server the shadowsocks-mirror-server is inside the firewall and GFW will only see one connection to
shadowsocks-server

can solve this problem?

**Comment by arthurkiller** [comment]
And, multi port is not recommend.

**Comment by houstar** [comment]
@arthurkiller 

> have you got any evidence?

I have two VPS outside GFW.  One was blocked by GFW since this One connected via multiple android ss client. The other wasn't blocked by GFW since they are connected for personal use and just one android ss-client connected to it.

> solve this problem

YES. it works fine for me till now.
Original:  multiple clients -> gfw -> one shadowsocks-server
This solution:  multiple clients -> one  shadowsocks-mirror-server -> gfw -> shadowsocks-server

> multi port is not recommend.

multi port comes from the original PR. Not this patch scope since shadowsocks-mirror-server provide
all the functionality that the shadowsocks-server did.

> The steps for using shadowsocks-mirror-server

1.  Start shadowsocks-server
2. Get the config.json from the shadowsocks-server
```
{
    "server":"9.9.9.9",
    "server_port":8388,
    "local_port":1080,
    "local_address":"127.0.0.1",
    "password":"barfoo!",
    "method": "aes-128-cfb",
    "timeout":600
```
3. Start shadowsocks-mirror-server

```
$ shadowsocks-mirror-server
2018/07/18 13:36:18 server listening port 8388 ...
2018/07/18 13:36:19 creating cipher for port: 8388
[DEBUG] 13:36:19 new client 127.0.0.1:60100->9.9.9.9:8388
[DEBUG] 13:36:19 new client 127.0.0.1:60101->9.9.9.9:8388
[DEBUG] 13:36:19 connecting www.youtube.com:443
[DEBUG] 13:36:19 connecting googleads.g.doubleclick.net:443
[DEBUG] 13:36:19 piping 127.0.0.1:60100<->www.youtube.com:443
[DEBUG] 13:36:19 piping 127.0.0.1:60101<->googleads.g.doubleclick.net:443
....
```

4. Start your android ss client to connect your shadocsocks-mirror-server. not connect to
    shadowsocks-server directly.

**Comment by arthurkiller** [comment]
> Original: multiple clients -> gfw -> one shadowsocks-server
> This solution: multiple clients -> one shadowsocks-mirror-server -> gfw -> shadowsocks-server

here maybe another approach. You can get your multi client access to single shadowsocks-client.

This solution: multiple clients -> one shadowsocks-local -> gfw -> shadowsocks-server

**Comment by arthurkiller** [comment]
> multi port comes from the original PR. Not this patch scope since shadowsocks-mirror-server provide
> all the functionality that the shadowsocks-server did.

htps://github.com/shadowsocks/shadowsocks-org/issues/54

**Comment by houstar** [comment]
> NOTICE: all you need is an authorization http proxy in front of your shadowsocks-local

I totally agree that with you.  but from customer's point of view, he/she must have additional works to setup an authorization http proxy.So this PR just mirror the shadowsocks-server to local address without any impacts on user experience. ;-)

**Comment by houstar** [comment]
let's go the pain point firstly. 

1.  multiple shadowsocks client to connect shadow-server will be detected by GFW.
2.  there is without any impacts on user experience if use shadowsocks-mirror-server

>  All you need is try to control your traffic on single ss-server.

If you have single ss-server, this is maybe the traffic control problem. but If we have multiple ss-server,
shadowsocks-mirror-server provided one interface for user and can be connect to multiple ss-server to reduce network traffic per  ss-server.

**Comment by arthurkiller** [comment]
Shadowsocks-server only focus on one thing: makes you anonymous. 

Any one can use this server freely as they like. this is not the problem caused by shadowsocks server.

If you think this could be a shadowsocks util tools. you should put up issues on shadowsocks-org for more help.

**Comment by arthurkiller** [comment]
you can combining shadowsocks server in whatever style you like.

**Comment by arthurkiller** [comment]
This PR will be closed, and you are freely to reopen it.

Thx for your contribute.

**Pull request closed without merging**
