### PR TITLE
Feature add: URI for shadowsocks-local

### PR DESCRIPTION
**Pull request by XanthusL**

### CODE REVIEW

**Comment by XanthusL** [comment]
>The command "go get github.com/aead/chacha20" failed and exited with 2 during .

But I have no idea with that, any suggestions?

I'll close and reopen this PR to triger a new build

**Comment by arthurkiller** [comment]
I will have a look on this

**Comment by XanthusL** [comment]
Maybe the problem is `chacha20/chacha/chachaAVX2_amd64.s` , but I know little about asm

**Comment by arthurkiller** [comment]
@XanthusL You should put up Pull Reuquest based on `master`

**Comment by XanthusL** [comment]
@arthurkiller OK, I'll open a new PR

**Pull request closed without merging**
