### PR TITLE
update the ss-go into v2

### PR DESCRIPTION
**Pull request by arthurkiller**
#192

### CODE REVIEW

**Comment by arthurkiller** [comment]
@lixin9311  the CI has a littlt bug caused by the go environment 
and the project dependency should be changed after the merge

**Comment by arthurkiller** [comment]
@lixin9311  and I don't know if you can du the merge?

**Comment by arthurkiller** [comment]
@cyfdecyf Could you please review the code if have the merge rights

**Comment by lixin9311** [comment]
please push to develop branch, not master

**Comment by arthurkiller** [comment]
@lixin9311  ok I will start another PR with this

**Pull request closed without merging**
